<table style="margin: 0px; width: 100%;">
  <tr>
    <td ><h1> Add Path Nodes! </h1> </td>
    <td ><a href="dataport" class="top-menu"><span class="glyphicon glyphicon-search"></span>Search DataPort</a></td>
  </tr>
</table> 
<div class="container-fluid">
  <div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
      <?php for ($i = 1; $i<=6; $i++) { ?>
        <li><a id="<?php echo $i; ?>" class="router" data-toggle="pill" href="#Level<?php echo $i; ?>"><h2>Level <?php echo $i; ?></h2></a></li>
      <?php } ?>
    </ul>
  </div>
  <div class="tab-content col-sm-9 col-md-10">
   <!-- <h4>{{ path_list }} </h4> -->
    <h3 style="color: blue"> Add a Node </h3>
    <h4 style="color: red"><?php echo $error ?> </h4>
    <div class="row">
      <form class="search navbar-form navbar-left" method='post'>
        <p style="color: red">Please select level, enter node name and click coordinates</p>
        <table class="table">
          <thead>
            <tr>
              <th style="text-align: center;">Floor</th>
              <th style="text-align: center;">Node Name</th>
              <th style="text-align: center;">X Coordinate</th>
              <th style="text-align: center;">Y Coordinates</th>
              <th style="text-align: center;"></th>
              <th style="text-align: center;"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <input type="number" id="floor" name="floor" class="form-control" placeholder="floor:"  required="true" readonly>
              </td>
              <td>
                <input type="text" name="node_name" id="node_name" class="form-control" placeholder="Node Name: floor + var"  required="true">
              </td>
              <td>
                <input type="text" name="x_add" id="x_add" class="form-control" placeholder="x..." required="true" readonly>
              </td>
              <td>
                <input type="text" name="y_add" id="y_add" class="form-control" placeholder="y..." required="true" readonly>
              </td>
              <td>
                <input type="hidden" name="form_name" value="AddNode">
              </td>
              <td>
                <input class="btn btn-primary" type='submit' id="Add" name="Add" value="Add Note">
              </td>
            </tr>
          </tbody>
        </table> 
      </form> 
    </div>
  
    <?php for ( $i = 1; $i<=6; $i++) { ?>
      <div id="Level<?php echo $i; ?>" class="col-sm-8 tab-pane fade">
      <?php switch ($i) {
        case 1: ?>
          <canvas id="canvas<?php echo $i; ?>" class="map" width='1011' height='1040'></canvas>
          <?php break; 
        default: ?>
          <canvas id="canvas<?php echo $i; ?>" class="map" width='677' height='1040'></canvas>
          <?php break;
       } ?>
        <div id="marker<?php echo $i; ?>" class="marker glyphicon glyphicon-remove-circle"></div>
      </div>
    <?php } ?>

  </div>
  <p>&nbsp;</p>

  <div class="tab-content col-sm-9 col-md-10">
    <h3 style="color: blue"> Manage Edges </h3>
    <h4 style="color: red"><?php echo $edgeerror ?> </h4>
    <p style="color: blue">FYI: If you plan to add or delete <b>a lot</b> of edges, suggest you use MySQL query/queries script. </p>
    <p style="color: blue"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  An edge is undirected. Therefore A=>B or B => A is equivalent to A <=> B.</p>
    <div class="row">
      <form class="search navbar-form navbar-left" method='post'>
        <p style="color: red">Please select level, Start Node and End Node. </p>
        <table class="table">
          <thead>
            <tr>
              <th style="text-align: center;">Floor</th>
              <th style="text-align: center;">Start Node</th>
              <th style="text-align: center;">End Node</th>
              <th style="text-align: center;"></th>
              <th style="text-align: center;"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <select id="EdgeFloor" name="EdgeFloor" > 
                  <?php for ( $i = 1; $i<=6; $i++) { ?>
                    <option value="<?php echo $i; ?>" <?php if ($edge_floor == $i) { ?> selected="selected" <?php ;} ?> >Level <?php echo $i; ?></option>
                  <?php } ?>
                </select>
              </td>
              <td>
                <select id="StartNode" name="StartNode">
                  <?php if ($node_list != null) { ?> 
                    <?php foreach ($node_list as $node) : ?>
                      <option value="<?php echo $node->id; ?>" <?php if ($node->id == $StartNode){ ?> selected="selected" <?php ;} ?> ><?php echo $node->name; ?></option>
                    <?php endforeach ?>
                  <?php } ?> 
                </select>  
              </td>
              <td>
                <select id="EndNode" name="EndNode">
                  <?php if ($node_list != null) { ?> 
                    <?php foreach ($node_list as $node) : ?>
                      <option value="<?php echo $node->id; ?>" <?php if ($node->id == $EndNode){ ?> selected="selected" <?php ;} ?> ><?php echo $node->name; ?></option>
                    <?php endforeach ?>
                  <?php } ?> 
                </select>
              </td>
              <td>
                <input type="hidden" name="form_name" value="AddEdge">
              </td>
              <td>
                <input class="btn btn-primary" type='submit' id="Add" name="Add" value="Add Edge">
                <input class="btn btn-primary" type='submit' id="Delete" name="Delete" value="Delete Edge">
              </td>
            </tr>
          </tbody>
        </table>
      </form> 
      <form id="node_form" class="navbar-form navbar-right" method='post' style="display: none;">
        <input type="number" id="nodefloor" name="floor" value ="" >
        <input name="form_name" value="node_list">
      </form>
    </div>
  </div>  
</div>

<div class="static-images" style="display: none;">
    <?php for ( $i = 1; $i<=6; $i++) { ?>
    <?php switch ($i) {
      case 1: ?>
        <img id="image<?php echo $i; ?>" class="map" src="img/ECERF<?php echo $i; ?>_DataPort.png" height=1000 width=971 />
        <?php break; 
      default: ?>
        <img id="image<?php echo $i; ?>" class="map" src="img/ECERF<?php echo $i; ?>_DataPort.png" height=1000 width=637 />
        <?php break;
     } ?>
  <?php } ?>
</div>
