<?php echo $this->doctype(); ?>

<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="en" class="ie ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="en" class="ie ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="en" class="ie ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate('ECERF DataPort Map'))->setSeparator(' - ')->setAutoEscape(false) ?>
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		<!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/dataport.ico'))
    				        //->headLink(array('rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/dataport.ico'))
                    ->prependStylesheet($this->basePath() . '/css/site.css')
                    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css') ?>
    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/addnote.js')
                                  ->prependFile($this->basePath() . '/js/ui.js')
                                  ->prependFile($this->basePath() . '/js/jqueryForm.js')
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
	</head>
	<body>
		<div class="container" style="margin-left: 100px; width : 90%; ">
      <?php echo $this->content; ?>
      <hr>
      <footer style="text-align: center">
          <p>&copy; 2005 - <?php echo date("Y", time()); ?> <a class="ualberta" href="https://www.ualberta.ca/">University of Alberta</a> <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
    
	</body>
</html>



